import { StyleSheet } from 'react-native';
import { Colors, lightColors, darkColors } from './colors';

const createStyles = (theme: Colors) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  customHeader: {
    height: 60,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.borderLight,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.textPrimary,
  },
  progressContainer: {
    paddingHorizontal: 20,
    paddingTop: 15,
    backgroundColor: theme.card,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  progressStepText: {
    fontSize: 10,
    fontWeight: '800',
    color: theme.secondary,
    letterSpacing: 0.5,
  },
  progressTitleText: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.textPrimary,
  },
  progressBarBg: {
    height: 6,
    backgroundColor: theme.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.secondary,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  container: {
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  stepContent: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
  },
  inputGroup: {
    marginBottom: 20,
    width: '100%',
    position: 'relative',
    zIndex: 10,
  },
  inputRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 16,
    paddingHorizontal: 14,
    height: 52,
    backgroundColor: theme.background,
  },
  inputIcon: {
    marginRight: 10,
  },
  inputCurrencyPrefix: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.textSecondary,
    marginRight: 6,
  },
  inputCurrencySuffix: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.textSecondary,
    marginLeft: 6,
  },
  textInput: {
    flex: 1,
    fontSize: 15,
    color: theme.textPrimary,
    fontWeight: '600',
  },
  inputError: {
    borderColor: theme.danger,
    backgroundColor: theme.dangerBackground,
  },
  errorText: {
    fontSize: 12,
    color: theme.danger,
    fontWeight: '600',
    marginTop: 6,
    marginLeft: 4,
  },
  formInputGroup: {
    marginBottom: 14,
  },
  formInputLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: theme.textSecondary,
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  formInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    backgroundColor: theme.background,
    paddingHorizontal: 12,
    height: 48,
  },
  formInputIcon: {
    marginRight: 8,
  },
  formTextInput: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  verticalDropdownContainer: {
    marginTop: 8,
    backgroundColor: theme.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  suggestionRowSymbol: {
    fontSize: 13,
    fontWeight: '700',
    color: theme.textPrimary,
  },
  suggestionRowBadge: {
    fontSize: 10,
    fontWeight: '600',
    color: theme.primary,
    backgroundColor: theme.borderLight,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    overflow: 'hidden',
  },
  dropdownEmptyText: {
    textAlign: 'center',
    paddingVertical: 16,
    color: theme.textSecondary,
    fontSize: 13,
  },
  leverageIndicatorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.successBackground,
    borderWidth: 1,
    borderColor: theme.success,
    padding: 12,
    borderRadius: 14,
    marginBottom: 20,
    gap: 8,
  },
  leverageIndicatorText: {
    fontSize: 13,
    color: theme.success,
    flex: 1,
  },
  exitStrategyBox: {
    marginBottom: 20,
  },
  exitHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  tabToggleBg: {
    flexDirection: 'row',
    backgroundColor: theme.borderLight,
    borderRadius: 10,
    padding: 3,
  },
  toggleBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  toggleBtnActive: {
    backgroundColor: theme.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  toggleBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  toggleBtnTextActive: {
    color: theme.textPrimary,
    fontWeight: '700',
  },
  primaryActionButton: {
    backgroundColor: theme.secondary,
    height: 52,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 10,
    shadowColor: theme.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  daysHeldPreviewBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.border,
    borderStyle: 'dashed',
    padding: 14,
    borderRadius: 16,
    marginBottom: 20,
  },
  daysHeldPreviewLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: theme.textSecondary,
  },
  daysHeldBadge: {
    backgroundColor: theme.borderLight,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  daysHeldBadgeText: {
    fontSize: 13,
    fontWeight: '800',
    color: theme.secondary,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
  },
  secondaryActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 16,
    height: 52,
    gap: 6,
  },
  secondaryActionText: {
    color: theme.textSecondary,
    fontSize: 15,
    fontWeight: '700',
  },
  calculateActionButton: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.success,
    borderRadius: 16,
    height: 52,
    gap: 6,
    shadowColor: theme.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  calculateActionText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  resultsContainer: {
    width: '100%',
  },
  headlineCard: {
    borderRadius: 28,
    padding: 24,
    alignItems: 'center',
    borderWidth: 1,
    marginBottom: 20,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
  },
  headlineCardProfit: {
    backgroundColor: theme.successBackground,
    borderColor: theme.success,
    shadowColor: theme.success,
  },
  headlineCardLoss: {
    backgroundColor: theme.dangerBackground,
    borderColor: theme.danger,
    shadowColor: theme.danger,
  },
  iconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  iconCircleProfit: {
    backgroundColor: theme.success,
  },
  iconCircleLoss: {
    backgroundColor: theme.danger,
  },
  headlineLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 4,
  },
  headlinePnLValue: {
    fontSize: 36,
    fontWeight: '900',
    marginBottom: 10,
  },
  textProfit: {
    color: theme.success,
  },
  textLoss: {
    color: theme.danger,
  },
  roiBadge: {
    borderRadius: 100,
    paddingHorizontal: 14,
    paddingVertical: 5,
    marginBottom: 20,
  },
  roiBadgeProfit: {
    backgroundColor: theme.successBackground,
  },
  roiBadgeLoss: {
    backgroundColor: theme.dangerBackground,
  },
  roiBadgeText: {
    fontSize: 13,
    fontWeight: '800',
  },
  roiBadgeTextProfit: {
    color: theme.success,
  },
  roiBadgeTextLoss: {
    color: theme.danger,
  },
  resultActionsRow: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
  },
  resultAdjustBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.card,
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 14,
    height: 46,
    gap: 6,
  },
  resultAdjustBtnText: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  resultResetBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.textPrimary,
    borderRadius: 14,
    height: 46,
    gap: 6,
  },
  resultResetBtnText: {
    color: theme.background,
    fontSize: 14,
    fontWeight: '700',
  },
  resultsDetailCard: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: theme.borderLight,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
  },
  resultsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 16,
  },
  resultsDetailCardTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: theme.textPrimary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  detailLabel: {
    fontSize: 13,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  detailValue: {
    fontSize: 13,
    color: theme.textPrimary,
    fontWeight: '600',
  },
  detailValueBold: {
    fontSize: 14,
    color: theme.textPrimary,
    fontWeight: '800',
  },
  rowDivider: {
    height: 1,
    backgroundColor: theme.borderLight,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalCalendarContainer: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: 20,
    width: '100%',
    maxWidth: 340,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  calendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthText: {
    fontSize: 16,
    fontWeight: '700',
    color: theme.textPrimary,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarHeaderDayCell: {
    width: '14.28%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  calendarHeaderDayText: {
    fontSize: 12,
    fontWeight: '600',
    color: theme.textSecondary,
  },
  calendarDayCell: {
    width: '14.28%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  selectedDayCell: {
    backgroundColor: theme.primary,
  },
  calendarDayText: {
    fontSize: 13,
    fontWeight: '500',
    color: theme.textPrimary,
  },
  selectedDayText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  pastDayCell: {
    backgroundColor: 'transparent',
  },
  pastDayText: {
    color: theme.disabledText,
    textDecorationLine: 'none',
    opacity: 0.4,
  },
  calendarCloseBtn: {
    marginTop: 16,
    backgroundColor: theme.borderLight,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  calendarCloseBtnText: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.textSecondary,
  },
});

const lightStyles = createStyles(lightColors);
const darkStyles = createStyles(darkColors);

export const useCalculatorStyles = (isDarkMode: boolean) => {
  return isDarkMode ? darkStyles : lightStyles;
};
