import { ScaledSheet } from 'react-native-size-matters';
import { Colors, darkColors, lightColors } from './colors';

const createStyles = (theme: Colors) => ScaledSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  customHeader: {
    height: 60,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '16@ms',
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.borderLight,
  },
  headerTitle: {
    fontSize: '18@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  progressContainer: {
    paddingHorizontal: '20@ms',
    paddingTop: '15@ms',
    backgroundColor: theme.card,
    paddingBottom: '15@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  progressHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '8@ms',
    marginBottom: '8@vs',
  },
  progressStepText: {
    fontSize: '10@ms',
    fontWeight: '800',
    color: theme.secondary,
    letterSpacing: 0.5,
  },
  progressTitleText: {
    fontSize: '13@ms',
    fontWeight: '700',
    color: theme.textPrimary,
    flexShrink: 1,
    textAlign: 'right',
  },
  progressBarBg: {
    height: 6,
    backgroundColor: theme.border,
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: theme.secondary,
  },
  keyboardFrame: {
    flex: 1,
    minHeight: 0,
  },
  scrollContainer: {
    flexGrow: 1,
    paddingBottom: '40@ms',
  },
  resultsScrollContainer: {
    flexGrow: 0,
    paddingBottom: '24@ms',
  },
  container: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    paddingTop: '20@ms',
  },
  resultsContentContainer: {
    flexGrow: 0,
    flexShrink: 0,
  },
  stepContent: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: '20@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
  },
  inputGroup: {
    marginBottom: '20@vs',
    width: '100%',
    position: 'relative',
    zIndex: 10,
  },
  inputRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: '16@ms',
    marginBottom: '20@vs',
  },
  inputLabel: {
    fontSize: '11@ms',
    fontWeight: '700',
    color: theme.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: '8@vs',
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 16,
    paddingHorizontal: '14@ms',
    height: 52,
    backgroundColor: theme.background,
  },
  inputIcon: {
    marginRight: '10@ms',
  },
  inputCurrencyPrefix: {
    fontSize: '16@ms',
    fontWeight: '700',
    color: theme.textSecondary,
    marginRight: '6@ms',
  },
  inputCurrencySuffix: {
    fontSize: '16@ms',
    fontWeight: '700',
    color: theme.textSecondary,
    marginLeft: '6@ms',
  },
  textInput: {
    flex: 1,
    fontSize: '15@ms',
    color: theme.textPrimary,
    fontWeight: '600',
  },
  inputError: {
    borderColor: theme.danger,
    backgroundColor: theme.dangerBackground,
  },
  errorText: {
    fontSize: '12@ms',
    color: theme.danger,
    fontWeight: '600',
    marginTop: '6@vs',
    marginLeft: '4@ms',
  },
  formInputGroup: {
    marginBottom: '14@vs',
  },
  formInputLabel: {
    fontSize: '10@ms',
    fontWeight: '800',
    color: theme.textSecondary,
    letterSpacing: 0.8,
    marginBottom: '6@vs',
  },
  formInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    backgroundColor: theme.background,
    paddingHorizontal: '12@ms',
    height: 48,
  },
  formInputIcon: {
    marginRight: '8@ms',
  },
  formTextInput: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: '13@ms',
    fontWeight: '600',
  },
  verticalDropdownContainer: {
    marginTop: '8@vs',
    backgroundColor: theme.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '14@ms',
    paddingVertical: '10@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  suggestionRowSymbol: {
    fontSize: '13@ms',
    fontWeight: '700',
    color: theme.textPrimary,
    flexShrink: 1,
  },
  suggestionRowBadge: {
    fontSize: '10@ms',
    fontWeight: '600',
    color: theme.primary,
    backgroundColor: theme.borderLight,
    paddingHorizontal: '6@ms',
    paddingVertical: '2@ms',
    borderRadius: 4,
    overflow: 'hidden',
  },
  dropdownEmptyText: {
    textAlign: 'center',
    paddingVertical: '16@ms',
    color: theme.textSecondary,
    fontSize: '13@ms',
  },
  leverageIndicatorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.successBackground,
    borderWidth: 1,
    borderColor: theme.success,
    padding: '12@ms',
    borderRadius: 14,
    marginBottom: '20@vs',
    gap: '8@ms',
  },
  leverageIndicatorText: {
    fontSize: '13@ms',
    color: theme.success,
    flex: 1,
  },
  exitStrategyBox: {
    marginBottom: '20@vs',
  },
  exitHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: '8@ms',
    marginBottom: '10@vs',
  },
  tabToggleBg: {
    flexDirection: 'row',
    flexShrink: 1,
    backgroundColor: theme.borderLight,
    borderRadius: 10,
    padding: '3@ms',
  },
  toggleBtn: {
    flex: 1,
    minWidth: '92@ms',
    paddingHorizontal: '12@ms',
    paddingVertical: '6@ms',
    borderRadius: 8,
  },
  toggleBtnActive: {
    backgroundColor: theme.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 1,
  },
  toggleBtnText: {
    fontSize: '11@ms',
    fontWeight: '600',
    color: theme.textSecondary,
    textAlign: 'center',
  },
  toggleBtnTextActive: {
    color: theme.textPrimary,
    fontWeight: '700',
  },
  primaryActionButton: {
    backgroundColor: theme.secondary,
    height: 52,
    borderRadius: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8@ms',
    marginTop: '10@vs',
    shadowColor: theme.secondary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  primaryActionText: {
    color: '#ffffff',
    fontSize: '15@ms',
    fontWeight: '700',
  },
  daysHeldPreviewBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.border,
    borderStyle: 'dashed',
    padding: '14@ms',
    borderRadius: 16,
    marginBottom: '20@vs',
  },
  daysHeldPreviewLabel: {
    fontSize: '12@ms',
    fontWeight: '700',
    color: theme.textSecondary,
    flexShrink: 1,
  },
  daysHeldBadge: {
    backgroundColor: theme.borderLight,
    borderRadius: 8,
    paddingHorizontal: '10@ms',
    paddingVertical: '5@ms',
  },
  daysHeldBadgeText: {
    fontSize: '13@ms',
    fontWeight: '800',
    color: theme.secondary,
  },
  actionButtonsRow: {
    flexDirection: 'row',
    gap: '12@ms',
    marginTop: '10@vs',
  },
  secondaryActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: theme.border,
    borderRadius: 16,
    height: 52,
    gap: '6@ms',
  },
  secondaryActionText: {
    color: theme.textSecondary,
    fontSize: '15@ms',
    fontWeight: '700',
  },
  calculateActionButton: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.success,
    borderRadius: 16,
    height: 52,
    gap: '6@ms',
    shadowColor: theme.success,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  calculateActionText: {
    color: '#ffffff',
    fontSize: '15@ms',
    fontWeight: '700',
  },
  resultsContainer: {
    width: '100%',
    flexGrow: 0,
    flexShrink: 0,
  },
  headlineCard: {
    backgroundColor: theme.card,
    borderRadius: 22,
    padding: '20@ms',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: '20@vs',
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 15,
    elevation: 4,
  },
  headlineCardProfit: {
    borderTopWidth: 4,
    borderTopColor: theme.success,
  },
  headlineCardLoss: {
    borderTopWidth: 4,
    borderTopColor: theme.danger,
  },
  iconCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '12@vs',
  },
  iconCircleProfit: {
    backgroundColor: theme.success,
  },
  iconCircleLoss: {
    backgroundColor: theme.danger,
  },
  headlineLabel: {
    fontSize: '11@ms',
    fontWeight: '800',
    color: theme.textSecondary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom: '4@vs',
  },
  headlinePnLValue: {
    fontSize: '34@ms',
    fontWeight: '900',
    marginBottom: '12@vs',
    textAlign: 'center',
    letterSpacing: 0,
  },
  textProfit: {
    color: theme.success,
  },
  textLoss: {
    color: theme.danger,
  },
  roiBadge: {
    borderRadius: 100,
    paddingHorizontal: '14@ms',
    paddingVertical: '6@ms',
    marginBottom: '18@vs',
    borderWidth: 1,
  },
  roiBadgeProfit: {
    backgroundColor: theme.successBackground,
    borderColor: theme.success,
  },
  roiBadgeLoss: {
    backgroundColor: theme.dangerBackground,
    borderColor: theme.danger,
  },
  roiBadgeText: {
    fontSize: '13@ms',
    fontWeight: '800',
  },
  roiBadgeTextProfit: {
    color: theme.success,
  },
  roiBadgeTextLoss: {
    color: theme.danger,
  },
  resultActionsRow: {
    flexDirection: 'row',
    gap: '10@ms',
    width: '100%',
  },
  resultAdjustBtn: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.borderLight,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    minHeight: 48,
    gap: '6@ms',
    paddingHorizontal: '10@ms',
  },
  resultAdjustBtnText: {
    color: theme.textPrimary,
    fontSize: '14@ms',
    fontWeight: '800',
  },
  resultResetBtn: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.primary,
    borderRadius: 12,
    minHeight: 48,
    gap: '6@ms',
    paddingHorizontal: '10@ms',
  },
  resultResetBtnText: {
    color: '#ffffff',
    fontSize: '14@ms',
    fontWeight: '800',
  },
  resultsDetailCard: {
    backgroundColor: theme.card,
    borderRadius: 20,
    paddingHorizontal: '18@ms',
    paddingVertical: '16@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
    gap: 0,
    marginTop: '12@vs',
  },
  resultsHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8@ms',
    marginBottom: '8@vs',
  },
  resultsDetailCardTitle: {
    fontSize: '12@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    minHeight: 36,
    paddingVertical: '7@vs',
    flexWrap: 'wrap',
    gap: '8@ms',
  },
  detailLabel: {
    fontSize: '13@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    flexShrink: 1,
  },
  detailValue: {
    fontSize: '13@ms',
    color: theme.textPrimary,
    fontWeight: '600',
    flexShrink: 1,
  },
  detailValueBold: {
    fontSize: '14@ms',
    color: theme.textPrimary,
    fontWeight: '800',
    flexShrink: 1,
  },
  rowDivider: {
    height: 1,
    backgroundColor: theme.borderLight,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: '20@ms',
  },
  modalCalendarContainer: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '20@ms',
    width: '100%',
    maxWidth: 340,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16@vs',
  },
  calendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthText: {
    fontSize: '16@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarHeaderDayCell: {
    width: '14.28%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: '8@ms',
  },
  calendarHeaderDayText: {
    fontSize: '12@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
  calendarDayCell: {
    width: '14.28%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  selectedDayCell: {
    backgroundColor: theme.primary,
  },
  calendarDayText: {
    fontSize: '13@ms',
    fontWeight: '500',
    color: theme.textPrimary,
  },
  selectedDayText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  pastDayCell: {
    backgroundColor: 'transparent',
  },
  pastDayText: {
    color: theme.disabledText,
    textDecorationLine: 'none',
    opacity: 0.4,
  },
  calendarCloseBtn: {
    marginTop: '16@vs',
    backgroundColor: theme.borderLight,
    borderRadius: 12,
    paddingVertical: '12@ms',
    alignItems: 'center',
  },
  calendarCloseBtnText: {
    fontSize: '14@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
});

const lightStyles = createStyles(lightColors);
const darkStyles = createStyles(darkColors);

export const useCalculatorStyles = (isDarkMode: boolean) => {
  return isDarkMode ? darkStyles : lightStyles;
};
