import { StyleSheet } from 'react-native';
import { Colors, lightColors, darkColors } from './colors';

const createStyles = (theme: Colors) => StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 15,
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 25,
  },
  welcomeText: {
    fontSize: 16,
    color: theme.textSecondary,
    fontWeight: '500',
  },
  nameText: {
    fontSize: 28,
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.5,
  },
  profileButton: {
    padding: 4,
    borderRadius: 50,
    backgroundColor: theme.borderLight,
  },
  card: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  centeredCard: {
    minHeight: 180,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    color: theme.textSecondary,
    fontSize: 14,
    fontWeight: '500',
  },
  errorText: {
    color: theme.danger,
    fontSize: 14,
    fontWeight: '600',
  },
  retryButton: {
    backgroundColor: theme.border,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    marginTop: 4,
  },
  retryText: {
    color: theme.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  cardTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cardTitle: {
    color: theme.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: 0.5,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 99,
    gap: 4,
  },
  bullishBadge: {
    backgroundColor: theme.successBackground,
  },
  bearishBadge: {
    backgroundColor: theme.dangerBackground,
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  bullishDot: {
    backgroundColor: theme.success,
  },
  bearishDot: {
    backgroundColor: theme.danger,
  },
  badgeText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  bullishBadgeText: {
    color: theme.success,
  },
  bearishBadgeText: {
    color: theme.danger,
  },
  cardBody: {
    marginBottom: 20,
  },
  indexName: {
    color: theme.darkCardSubtext,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
  },
  indexPrice: {
    color: theme.textPrimary,
    fontSize: 36,
    fontWeight: '800',
    letterSpacing: -1,
  },
  changeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  indexChange: {
    fontSize: 14,
    fontWeight: '600',
  },
  divider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.08)',
    marginBottom: 16,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerCol: {
    alignItems: 'flex-start',
  },
  footerLabel: {
    color: theme.iconMuted,
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  footerVal: {
    color: theme.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  screenerButton: {
    backgroundColor: theme.card,
    borderRadius: 18,
    paddingVertical: 16,
    paddingHorizontal: 20,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 4,
  },
  screenerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  screenerButtonText: {
    color: theme.textPrimary,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  zerodhaButton: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
    minHeight: 100,
  },
  zerodhaContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  zerodhaButtonText: {
    color: theme.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  calculatorButton: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 20,
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
    minHeight: 100,
  },
  calculatorContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  calculatorButtonText: {
    color: theme.textPrimary,
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  bigCardIconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bigCardSubText: {
    color: theme.darkCardSubtext,
    fontSize: 12,
    marginTop: 4,
    fontWeight: '500',
  },
  sideMenuOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    zIndex: 99999,
  },
  backdrop: {
    flex: 1,
    backgroundColor: theme.overlay,
  },
  drawerPanel: {
    width: '80%',
    height: '100%',
    backgroundColor: theme.background,
    shadowColor: '#000',
    shadowOffset: { width: -8, height: 0 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 24,
  },
  drawerHeader: {
    paddingTop: 35,
    height: 95,
    backgroundColor: theme.card,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  drawerBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.borderLight,
  },
  drawerHeaderTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: theme.textPrimary,
  },
  drawerBody: {
    flex: 1,
    padding: 20,
    backgroundColor: theme.background,
  },
  profileDetailsCard: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  avatarCircle: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: 'rgba(79, 70, 229, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  avatarCircleGray: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: theme.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  profileLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: theme.textSecondary,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  profileEmail: {
    fontSize: 16,
    fontWeight: '800',
    color: theme.textPrimary,
    marginBottom: 8,
    textAlign: 'center',
  },
  profileSubtext: {
    fontSize: 13,
    color: theme.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
    marginBottom: 16,
  },
  profileDivider: {
    height: 1,
    backgroundColor: theme.borderLight,
    width: '100%',
    marginVertical: 16,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    marginBottom: 24,
    backgroundColor: theme.background,
    padding: 12,
    borderRadius: 12,
  },
  featureText: {
    fontSize: 13,
    fontWeight: '600',
    color: theme.textPrimary,
  },
  drawerLoginButton: {
    backgroundColor: theme.darkCard,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  loginButtonText: {
    color: theme.darkCardText,
    fontSize: 15,
    fontWeight: '700',
  },
  drawerSettingsButton: {
    backgroundColor: theme.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    width: '100%',
    marginBottom: 12,
  },
  settingsButtonText: {
    color: theme.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  drawerLogoutButton: {
    backgroundColor: theme.danger,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 14,
    width: '100%',
    shadowColor: theme.danger,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  logoutButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  headerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
  },
  profileButtonWithImage: {
    padding: 0,
    overflow: 'hidden',
  },
  drawerAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  themeToggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: theme.background,
    borderRadius: 14,
    marginBottom: 16,
  },
  themeToggleLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: theme.textPrimary,
  }
});

const lightStyles = createStyles(lightColors);
const darkStyles = createStyles(darkColors);

export const useIndexStyles = (isDarkMode: boolean) => {
  return isDarkMode ? darkStyles : lightStyles;
};
