import { MD3LightTheme, MD3DarkTheme, MD3Theme } from 'react-native-paper';
import { lightColors, darkColors } from './colors';

export const paperLightTheme: MD3Theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: lightColors.primary,
    onPrimary: '#ffffff',
    primaryContainer: lightColors.primaryBackground,
    onPrimaryContainer: lightColors.primary,
    secondary: lightColors.primary,
    onSecondary: '#ffffff',
    secondaryContainer: lightColors.primaryBackground,
    onSecondaryContainer: lightColors.primary,
    tertiary: lightColors.primary,
    tertiaryContainer: lightColors.primaryBackground,
    onTertiaryContainer: lightColors.primary,
    background: lightColors.background,
    onBackground: lightColors.textPrimary,
    surface: lightColors.card,
    onSurface: lightColors.textPrimary,
    surfaceVariant: lightColors.borderLight,
    onSurfaceVariant: lightColors.textSecondary,
    surfaceDisabled: lightColors.borderLight,
    onSurfaceDisabled: lightColors.placeholder,
    outline: lightColors.border,
    outlineVariant: lightColors.borderLight,
    error: lightColors.danger,
    onError: '#ffffff',
    errorContainer: lightColors.dangerBackground,
    onErrorContainer: lightColors.danger,
    elevation: {
      level0: 'transparent',
      level1: lightColors.card,
      level2: lightColors.card,
      level3: lightColors.card,
      level4: lightColors.card,
      level5: lightColors.card,
    },
  },
};

export const paperDarkTheme: MD3Theme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: darkColors.primary,
    onPrimary: '#ffffff',
    primaryContainer: darkColors.primaryBackground,
    onPrimaryContainer: darkColors.primary,
    secondary: darkColors.primary,
    onSecondary: '#ffffff',
    secondaryContainer: darkColors.primaryBackground,
    onSecondaryContainer: darkColors.primary,
    tertiary: darkColors.primary,
    tertiaryContainer: darkColors.primaryBackground,
    onTertiaryContainer: darkColors.primary,
    background: darkColors.background,
    onBackground: darkColors.textPrimary,
    surface: darkColors.card,
    onSurface: darkColors.textPrimary,
    surfaceVariant: darkColors.borderLight,
    onSurfaceVariant: darkColors.textSecondary,
    surfaceDisabled: darkColors.borderLight,
    onSurfaceDisabled: darkColors.placeholder,
    outline: darkColors.border,
    outlineVariant: darkColors.borderLight,
    error: darkColors.danger,
    onError: '#ffffff',
    errorContainer: darkColors.dangerBackground,
    onErrorContainer: darkColors.danger,
    elevation: {
      level0: 'transparent',
      level1: darkColors.card,
      level2: darkColors.card,
      level3: darkColors.card,
      level4: darkColors.card,
      level5: darkColors.card,
    },
  },
};
