import { StyleSheet, Platform } from 'react-native';
import { ScaledSheet } from 'react-native-size-matters';
import { Colors, lightColors, darkColors } from './colors';

const createStyles = (theme: Colors) => ScaledSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  customHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '16@ms',
    paddingVertical: '12@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    backgroundColor: theme.card,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.borderLight,
  },
  headerTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8@ms',
  },
  headerTitle: {
    fontSize: '18@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.3,
  },
  securedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.successBackground,
    paddingHorizontal: '8@ms',
    paddingVertical: '3@ms',
    borderRadius: 6,
    gap: '4@ms',
  },
  securedText: {
    fontSize: '9@ms',
    fontWeight: '800',
    color: theme.success,
    letterSpacing: 0.5,
  },
  container: {
    flex: 1,
    paddingHorizontal: '20@ms',
    paddingTop: '15@ms',
  },
  centered: {
    justifyContent: 'center',
    alignItems: 'center',
    gap: '12@ms',
  },
  loadingText: {
    fontSize: '14@ms',
    color: theme.textSecondary,
    fontWeight: '600',
  },
  connectionCard: {
    backgroundColor: theme.darkCard,
    borderRadius: 20,
    padding: '16@ms',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 4,
    marginBottom: '20@vs',
  },
  connectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12@ms',
    flex: 1,
    marginRight: '8@ms',
  },
  kiteLogoPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: '#f05a28',
    alignItems: 'center',
    justifyContent: 'center',
  },
  kiteLogoText: {
    color: '#ffffff',
    fontSize: '22@ms',
    fontWeight: '900',
  },
  connectionTitle: {
    color: theme.darkCardText,
    fontSize: '15@ms',
    fontWeight: '700',
  },
  connectionSubtitle: {
    color: theme.darkCardSubtext,
    fontSize: '12@ms',
    fontWeight: '500',
    marginTop: '2@vs',
  },
  activeStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.successBackground,
    paddingHorizontal: '8@ms',
    paddingVertical: '5@ms',
    borderRadius: 20,
    gap: '4@ms',
  },
  activeDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.success,
  },
  activeStatusText: {
    color: theme.success,
    fontSize: '10@ms',
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  connectionClientCode: {
    color: theme.darkCardSubtext,
    fontSize: '11@ms',
    fontWeight: '600',
    marginTop: '2@vs',
  },
  inactiveStatusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.dangerBackground,
    paddingHorizontal: '8@ms',
    paddingVertical: '5@ms',
    borderRadius: 20,
    gap: '4@ms',
  },
  inactiveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: theme.danger,
  },
  inactiveStatusText: {
    color: theme.danger,
    fontSize: '10@ms',
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12@vs',
    marginTop: '8@vs',
  },
  sectionTitle: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.2,
  },
  syncButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6@ms',
    paddingVertical: '6@ms',
    paddingHorizontal: '12@ms',
    borderRadius: 10,
    backgroundColor: theme.primaryBackground,
  },
  syncText: {
    color: theme.primary,
    fontSize: '12@ms',
    fontWeight: '700',
  },
  marginCard: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '16@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    marginBottom: '20@vs',
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
  },
  marginRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: '8@ms',
  },
  marginCol: {
    flex: 1,
    gap: '4@ms',
  },
  marginDivider: {
    width: 1,
    backgroundColor: theme.border,
    marginHorizontal: '16@ms',
  },
  marginLabel: {
    color: theme.textSecondary,
    fontSize: '10@ms',
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  marginValue: {
    color: theme.textPrimary,
    fontSize: '16@ms',
    fontWeight: '800',
  },
  horizontalDivider: {
    height: 1,
    backgroundColor: theme.borderLight,
    marginVertical: '12@vs',
  },
  totalMarginRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  totalMarginLabel: {
    color: theme.textPrimary,
    fontSize: '13@ms',
    fontWeight: '700',
  },
  totalMarginValue: {
    color: theme.primary,
    fontSize: '18@ms',
    fontWeight: '800',
  },
  holdingsList: {
    gap: '12@ms',
    marginBottom: '20@vs',
  },
  holdingCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: '16@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.02,
    shadowRadius: 6,
    elevation: 1,
  },
  holdingTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  holdingSymbol: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.1,
  },
  holdingQty: {
    fontSize: '12@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    marginTop: '2@vs',
  },
  holdingLtpContainer: {
    alignItems: 'flex-end',
  },
  holdingLtpLabel: {
    fontSize: '9@ms',
    fontWeight: '800',
    color: theme.iconMuted,
    letterSpacing: 0.2,
  },
  holdingLtp: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    marginTop: '1@vs',
  },
  cardDivider: {
    height: 1,
    backgroundColor: theme.background,
    marginVertical: '12@vs',
  },
  holdingBottomRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  holdingStatLabel: {
    fontSize: '9@ms',
    fontWeight: '800',
    color: theme.textSecondary,
    letterSpacing: 0.5,
    marginBottom: '3@vs',
  },
  holdingStatVal: {
    fontSize: '13@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  holdingPnlContainer: {
    alignItems: 'flex-end',
  },
  holdingPnlValue: {
    fontSize: '14@ms',
    fontWeight: '800',
  },
  automationActionCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: '16@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '12@vs',
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.02,
    shadowRadius: 8,
    elevation: 2,
  },
  actionIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.primaryBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionTextContainer: {
    flex: 1,
    marginLeft: '12@ms',
    marginRight: '8@ms',
    gap: '2@ms',
  },
  actionTitle: {
    fontSize: '14@ms',
    fontWeight: '800',
    color: theme.textPrimary,
  },
  actionDesc: {
    fontSize: '11@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    lineHeight: 15,
  },
  formCard: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '20@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
    marginTop: '8@vs',
  },
  formHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: '12@ms',
    marginBottom: '20@vs',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    paddingBottom: '16@ms',
  },
  formTitle: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.2,
  },
  formSubtitle: {
    fontSize: '11@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    lineHeight: 15,
    marginTop: '4@vs',
  },
  inputGroup: {
    marginBottom: '16@vs',
    gap: '6@ms',
  },
  inputLabel: {
    fontSize: '9@ms',
    fontWeight: '800',
    color: theme.textSecondary,
    letterSpacing: 0.5,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    backgroundColor: theme.background,
    paddingHorizontal: '12@ms',
    height: 48,
  },
  inputIcon: {
    marginRight: '10@ms',
  },
  textInput: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: '13@ms',
    fontWeight: '600',
  },
  errorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6@ms',
    backgroundColor: theme.dangerBackground,
    padding: '10@ms',
    borderRadius: 10,
    marginBottom: '16@vs',
  },
  errorText: {
    color: theme.danger,
    fontSize: '12@ms',
    fontWeight: '600',
  },
  submitButton: {
    backgroundColor: theme.primary,
    height: 48,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8@ms',
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
    marginTop: '8@vs',
  },
  disabledButton: {
    backgroundColor: theme.disabledButton,
    shadowOpacity: 0,
    elevation: 0,
  },
  submitButtonText: {
    color: '#ffffff',
    fontSize: '13@ms',
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  connectCard: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '20@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
    marginTop: '8@vs',
  },
  connectHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: '12@ms',
    marginBottom: '16@vs',
  },
  warningIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.warningBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectTitle: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.2,
  },
  connectSubtitle: {
    fontSize: '11@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    lineHeight: 15,
    marginTop: '4@vs',
  },
  apiKeyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6@ms',
    backgroundColor: theme.background,
    paddingHorizontal: '12@ms',
    paddingVertical: '8@ms',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.border,
    marginBottom: '20@vs',
  },
  apiKeyBadgeText: {
    fontSize: '11@ms',
    fontWeight: '700',
    color: theme.textSecondary,
    fontFamily: Platform.OS === 'ios' ? 'Courier' : 'monospace',
  },
  connectButton: {
    backgroundColor: theme.primary,
    height: 48,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8@ms',
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 3,
  },
  connectButtonText: {
    color: '#ffffff',
    fontSize: '13@ms',
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  reconfigureButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6@ms',
    marginTop: '14@vs',
    paddingVertical: '8@ms',
  },
  reconfigureButtonText: {
    color: theme.textSecondary,
    fontSize: '12@ms',
    fontWeight: '700',
  },
  webViewContainer: {
    flex: 1,
    backgroundColor: theme.background,
  },
  webViewHeader: {
    height: 56,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '16@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
    backgroundColor: theme.card,
  },
  webViewCloseButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: theme.borderLight,
  },
  webViewHeaderTitle: {
    fontSize: '15@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  webViewLoaderContainer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successCard: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '20@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
    marginTop: '8@vs',
  },
  successHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: '12@ms',
    marginBottom: '8@vs',
  },
  successIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: theme.successBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successTitle: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.2,
  },
  successSubtitle: {
    fontSize: '11@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    lineHeight: 15,
    marginTop: '4@vs',
  },
  disconnectButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6@ms',
    marginTop: '16@vs',
    paddingVertical: '10@ms',
    backgroundColor: theme.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  disconnectButtonText: {
    color: theme.textSecondary,
    fontSize: '12@ms',
    fontWeight: '700',
  },
  blackCardConfigBtn: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verticalDropdownContainer: {
    marginTop: '8@vs',
    backgroundColor: theme.card,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: theme.border,
    overflow: 'hidden',
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  suggestionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: '14@ms',
    paddingVertical: '10@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  suggestionRowSymbol: {
    fontSize: '13@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  suggestionRowBadge: {
    fontSize: '10@ms',
    fontWeight: '600',
    color: theme.primary,
    backgroundColor: theme.primaryBackground,
    paddingHorizontal: '6@ms',
    paddingVertical: '2@ms',
    borderRadius: 4,
    overflow: 'hidden',
  },
  suggestionRowPrice: {
    fontSize: '12@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
  datePickerText: {
    fontSize: '14@ms',
    color: theme.textPrimary,
    fontWeight: '500',
    flex: 1,
    paddingVertical: '12@ms',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: '20@ms',
  },
  modalCalendarContainer: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '20@ms',
    width: '100%',
    maxWidth: 340,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  historyFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '6@vs',
  },
  historySectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBottom: '8@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    marginTop: '16@vs',
    marginBottom: '8@vs',
  },
  historySectionTitle: {
    fontSize: '13@ms',
    fontWeight: 'bold',
    color: theme.textPrimary,
    letterSpacing: 0.5,
  },
  historySectionBadge: {
    fontSize: '9@ms',
    fontWeight: '700',
    color: theme.primary,
    backgroundColor: theme.primaryBackground,
    paddingHorizontal: '8@ms',
    paddingVertical: '3@ms',
    borderRadius: 8,
    overflow: 'hidden',
  },
  emptyHistoryContainer: {
    paddingVertical: '24@ms',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8@ms',
  },
  emptyHistoryText: {
    fontSize: '11@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
  historyDividerSeparator: {
    height: 1,
    backgroundColor: theme.border,
    marginTop: '28@vs',
    marginBottom: '8@vs',
  },
  editModalContainer: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: '24@ms',
    width: '90%',
    maxWidth: 380,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 5,
  },
  editModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16@vs',
  },
  editModalTitle: {
    fontSize: '16@ms',
    fontWeight: '800',
    color: theme.textPrimary,
  },
  editModalCloseBtn: {
    padding: '4@ms',
  },
  calendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '16@vs',
  },
  calendarNavBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.borderLight,
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarMonthText: {
    fontSize: '16@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  calendarHeaderDayCell: {
    width: '14.28%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: '8@ms',
  },
  calendarHeaderDayText: {
    fontSize: '12@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
  calendarDayCell: {
    width: '14.28%',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
  },
  selectedDayCell: {
    backgroundColor: theme.primary,
  },
  calendarDayText: {
    fontSize: '13@ms',
    fontWeight: '500',
    color: theme.textPrimary,
  },
  selectedDayText: {
    color: '#ffffff',
    fontWeight: '700',
  },
  pastDayCell: {
    backgroundColor: 'transparent',
  },
  pastDayText: {
    color: theme.iconMuted,
    textDecorationLine: 'none',
    opacity: 0.4,
  },
  calendarCloseBtn: {
    marginTop: '16@vs',
    backgroundColor: theme.borderLight,
    borderRadius: 12,
    paddingVertical: '12@ms',
    alignItems: 'center',
  },
  calendarCloseBtnText: {
    fontSize: '14@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
  // Tab Bar Styles
  successMiniCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: '16@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    marginBottom: '16@vs',
  },
  profileMiniRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12@ms',
  },
  avatarCircle: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.primaryBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: theme.primary,
    fontSize: '14@ms',
    fontWeight: '800',
  },
  profileMiniName: {
    fontSize: '14@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  connectionIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '6@ms',
    marginTop: '2@vs',
  },
  connectionIndicatorText: {
    fontSize: '9@ms',
    fontWeight: '700',
    color: theme.success,
    letterSpacing: 0.5,
  },
  miniSettingsBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: theme.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: theme.border,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: theme.borderLight,
    borderRadius: 14,
    padding: '4@ms',
    marginBottom: '16@vs',
    gap: '4@ms',
  },
  tabButton: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2@ms',
    paddingVertical: '8@ms',
    borderRadius: 10,
  },
  activeTabButton: {
    backgroundColor: theme.card,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 4,
    elevation: 2,
  },
  tabButtonLabel: {
    fontSize: '11@ms',
    fontWeight: '700',
    color: theme.textSecondary,
    letterSpacing: 0.3,
  },
  activeTabButtonLabel: {
    color: theme.primary,
  },
  tabCard: {
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: '20@ms',
    borderWidth: 1,
    borderColor: theme.borderLight,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.04,
    shadowRadius: 12,
    elevation: 3,
  },
  tabCardTitle: {
    fontSize: '15@ms',
    fontWeight: '800',
    color: theme.textPrimary,
    letterSpacing: -0.2,
  },
  tabCardSubtitle: {
    fontSize: '11@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    lineHeight: 15,
    marginTop: '4@vs',
    marginBottom: '20@vs',
  },
  tradeTypeContainer: {
    flexDirection: 'row',
    backgroundColor: theme.borderLight,
    borderRadius: 12,
    padding: '4@ms',
    marginBottom: '16@vs',
    gap: '4@ms',
  },
  tradeTypeBtn: {
    flex: 1,
    paddingVertical: '12@ms',
    alignItems: 'center',
    borderRadius: 10,
  },
  buyActiveBtn: {
    backgroundColor: theme.success,
  },
  sellActiveBtn: {
    backgroundColor: theme.danger,
  },
  tradeTypeBtnText: {
    fontSize: '12@ms',
    fontWeight: '800',
    color: theme.textSecondary,
    letterSpacing: 0.5,
  },
  activeBtnText: {
    color: '#ffffff',
  },
  formInputGroup: {
    marginBottom: '14@vs',
  },
  formInputLabel: {
    fontSize: '10@ms',
    fontWeight: '800',
    color: theme.textSecondary,
    letterSpacing: 0.8,
    marginBottom: '6@vs',
  },
  formInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 12,
    backgroundColor: theme.background,
    paddingHorizontal: '12@ms',
    height: 48,
  },
  formInputIcon: {
    marginRight: '8@ms',
  },
  formTextInput: {
    flex: 1,
    color: theme.textPrimary,
    fontSize: '13@ms',
    fontWeight: '600',
  },
  formInputRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: '12@ms',
  },
  productTypeContainer: {
    flexDirection: 'row',
    gap: '8@ms',
    marginBottom: '20@vs',
  },
  productTypeBtn: {
    flex: 1,
    paddingVertical: '10@ms',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: theme.border,
    backgroundColor: theme.card,
  },
  productActiveBtn: {
    borderColor: theme.primary,
    backgroundColor: theme.primaryBackground,
  },
  productTypeBtnText: {
    fontSize: '11@ms',
    fontWeight: '700',
    color: theme.textSecondary,
  },
  productActiveText: {
    color: theme.primary,
  },
  executeBuyBtn: {
    backgroundColor: theme.success,
  },
  executeSellBtn: {
    backgroundColor: theme.danger,
  },
  executeActionBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '8@ms',
    borderRadius: 14,
    height: 52,
    shadowColor: theme.textPrimary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  executeActionBtnText: {
    color: '#ffffff',
    fontSize: '13@ms',
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  strategyItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: '14@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  strategyLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '12@ms',
    flex: 1,
  },
  stratIconCircle: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: theme.primaryBackground,
    alignItems: 'center',
    justifyContent: 'center',
  },
  strategyName: {
    fontSize: '13@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  strategyDesc: {
    fontSize: '10@ms',
    color: theme.textSecondary,
    fontWeight: '500',
    lineHeight: 14,
    marginTop: '2@vs',
  },
  historyList: {
    marginTop: '4@vs',
  },
  historyItem: {
    paddingVertical: '12@ms',
    borderBottomWidth: 1,
    borderBottomColor: theme.borderLight,
  },
  historyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  historyLeftInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: '8@ms',
  },
  historyTypeBadge: {
    paddingHorizontal: '6@ms',
    paddingVertical: '2@ms',
    borderRadius: 6,
  },
  historyBuyBadge: {
    backgroundColor: theme.successBackground,
  },
  historySellBadge: {
    backgroundColor: theme.dangerBackground,
  },
  historyTypeText: {
    fontSize: '9@ms',
    fontWeight: '800',
  },
  historyBuyText: {
    color: theme.success,
  },
  historySellText: {
    color: theme.danger,
  },
  historySymbolText: {
    fontSize: '12@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  historyQtyText: {
    fontSize: '11@ms',
    fontWeight: '600',
    color: theme.textSecondary,
  },
  statusBadge: {
    paddingHorizontal: '8@ms',
    paddingVertical: '3@ms',
    borderRadius: 20,
  },
  statusSuccessBadge: {
    backgroundColor: theme.successBackground,
  },
  statusConflictBadge: {
    backgroundColor: theme.warningBackground,
  },
  statusErrorBadge: {
    backgroundColor: theme.dangerBackground,
  },
  statusBadgeText: {
    fontSize: '9@ms',
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  statusSuccessText: {
    color: theme.success,
  },
  statusConflictText: {
    color: theme.warningText,
  },
  statusErrorText: {
    color: theme.danger,
  },
  historyTimestamp: {
    fontSize: '10@ms',
    color: theme.textSecondary,
    fontWeight: '500',
  },
  historyPriceText: {
    fontSize: '12@ms',
    fontWeight: '700',
    color: theme.textPrimary,
  },
  historyRejectReason: {
    fontSize: '9@ms',
    color: theme.danger,
    fontWeight: '600',
    marginTop: '4@vs',
  },
});

const lightStyles = createStyles(lightColors);
const darkStyles = createStyles(darkColors);

export const useZerodhaStyles = (isDarkMode: boolean) => {
  return isDarkMode ? darkStyles : lightStyles;
};
